# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d971d4f4287a072a0e99d503740d33593afe6164d2ad250aecd6e0ce45ed37f6d59d7ced4c4d0ba8a4a8a78f0284536b5694d319a8c5fac2d270f8f33c442dde

test:
  secret_key_base: 86511160cef373652eeeb8c597e4102335dd2a99dc844585be8ebe430ff852566319ea9a0e8f7f58445da09ec7938ebc07fc4cca5a6061f769e14aed6a5a8b30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
